#####################################################
# Common Filters 
#####################################################

[FILTER]
    Name             parser
    Match            marklogic.*.log
    Key_Name         filename
    Parser           ml_filename_shortener
    Preserve_Key     On
    Reserve_Data     On

[FILTER]
    Name             parser
    Match            marklogic.*.log
    Key_Name         file
    Parser           ml_port_type_parser
    Preserve_Key     On
    Reserve_Data     On

# Make fields lower case
[FILTER]
    Name             modify
    Match            marklogic.*.log
    Rename           Level level

# Add some new fields with fixed values for all logs
[FILTER]
    Name             record_modifier
    Match            marklogic.*.log
    Record           environment local
    #Record           environment {{ ml_environment }}

[FILTER]
    Name             record_modifier
    Match            marklogic.*.log
    Record           hostname ${HOSTNAME}

#####################################################
# ErrorLog filters 
#####################################################

[FILTER]
    Name             parser
    Match            marklogic.error.log
    Key_Name         log
    Parser           ml_error_infra_parser
    Parser           ml_error_memory_parser
    Parser           ml_error_memory_threshold_parser
    Parser           ml_error_catchall_parser
    Reserve_Data     On
    Preserve_Key     On

[FILTER]
    Name             rewrite_tag
    Match            marklogic.error.log
    Rule             $Message ^(Memory).*$ marklogic.memory.log false
    Emitter_Name     re_emitted

[FILTER]
    Name             lua
    Match            marklogic.error.log
    Script           marklogic.lua
    Call             remove_prefix

[FILTER]
    Name             modify
    Match            marklogic.error.log
    Rename           Message message

#####################################################
# AccessLog filters 
#####################################################

[FILTER]
    Name             modify
    Match            marklogic.access.log
    Rename           StatusCode status_code

[FILTER]
    Name             modify
    Match            marklogic.access.log
    Rename           IPAddress ip_address

[FILTER]
    Name             modify
    Match            marklogic.access.log
    Rename           Username username

[FILTER]
    Name             modify
    Match            marklogic.access.log
    Rename           Method method 

[FILTER]
    Name             modify
    Match            marklogic.access.log
    Rename           Url url

[FILTER]
    Name             modify
    Match            marklogic.access.log
    Rename           Protocol protocol

[FILTER]
    Name             modify
    Match            marklogic.access.log
    Rename           StatusCode status_code

[FILTER]
    Name             modify
    Match            marklogic.access.log
    Rename           ResponseSize response_size 

[FILTER]
    Name             modify
    Match            marklogic.access.log
    Rename           Referer referer

[FILTER]
    Name             modify
    Match            marklogic.access.log
    Rename           UserAgent useragent

#####################################################
# RequestLog filters 
#####################################################

[FILTER]
    Name             modify
    Match            marklogic.request.log
    Rename           elapsedTime elapsed_time
    Rename           runTime run_time


