# In dit bestand kunnen eventueel extra inputs worden meegeven aan fluentbit. Zie documentatie van fluentbit voor de juiste notatie
# vergeet niet fluentbit te herstarten na een wijziging.
# sudo systemctl restart fluent-bit

#[INPUT]
#    Name tail
#    Path ${ML_LOG_PATH}/CrashLog.txt
#    Read_from_head true
#    Tag kube.marklogic.logs.crash
#    Path_Key path
#    Mem_Buf_Limit 4MB
#
[INPUT]
    Name             tail
    Path             ${ML_LOG_PATH}/ErrorLog.txt,${ML_LOG_PATH}/*_*ErrorLog.txt
    Path_Key         filename
    Read_From_Head   true
    Multiline.Parser ml_error_multiline_parser
    Tag              marklogic.error.log
    Mem_Buf_Limit    4MB

[INPUT]
    Name             tail
    Path             ${ML_LOG_PATH}/AccessLog.txt,${ML_LOG_PATH}/*_*AccessLog.txt
    Exclude_Path     ${ML_LOG_PATH}/7997_AccessLog.txt
    Path_Key         filename
    Read_From_Head   true
    Parser           ml_access_log_parser
    Tag              marklogic.access.log
    Mem_Buf_Limit    4MB

[INPUT]
    Name             tail
    Path             ${ML_LOG_PATH}/RequestLog.txt,${ML_LOG_PATH}/*_*RequestLog.txt
    Path_Key         filename
    Read_From_Head   true
    Parser           json_parser
    Tag              marklogic.request.log
    Mem_Buf_Limit    4MB

